Email flow
debionetwork/debio-backend pull request #163
Opened 2021-12-09 18:22 UTC by JackyRahman

### Debio-1253
[https://blocksphere2020.atlassian.net/browse/DBIO-1253](https://blocksphere2020.atlassian.net/browse/DBIO-1253)

### [Back End] Lab Registration - Save Email Event using API

- fixing Lab Register Template.
- fixing customer service request template.
- create API for send mail Lab Register.
- create service fuction for mail.

2021-12-12 01:45 UTC, agustinustheo requested changes
Refactor this please.

2021-12-12 01:45 UTC, agustinustheo commented on src/common/mailer/mailer.manager.ts
> -import { Injectable } from '@nestjs/common';
This is the Mailer Manager, don't put the Substrate service code in here. Separate it somewhere else please.

2021-12-12 01:45 UTC, agustinustheo commented on src/common/mailer/mailer.controller.ts
> +import { Controller, OnModuleInit, Param, Post, Res } from "@nestjs/common";
Instead of putting it inside the Mailer manager, move the Substrate code here. Make them private, so it cannot be accessed externally.

2021-12-13 05:51 UTC, agustinustheo commented on src/common/mailer/mailer.controller.ts
> +import { Controller, OnModuleInit, Param, Post, Res } from "@nestjs/common";
Revision: Remove the `mailer.controller.ts` and create a new folder named `Email` to house the new API endpoints.

2021-12-14 06:42 UTC, agustinustheo requested changes

2021-12-14 06:42 UTC, agustinustheo commented on src/common/mailer/mailer.controller.ts
> +import { Controller, OnModuleInit, Param, Post, Res } from "@nestjs/common";
Don't make a `controller` inside the `common` folder.

2021-12-14 06:42 UTC, agustinustheo commented on src/common/mailer/mailer.manager.ts
> -import { Injectable } from '@nestjs/common';
Don't inject an `ApiPromise` inside the `mailer.manager.ts`. This file is specifically made for mail not Substrate.

2021-12-22 04:42 UTC, hilyds approved these changes
Please note that this PR will be approved first to catch up DeBio launch mainnet, but will become a tech debt for part that @agustinustheo 's comment

2021-12-22 06:08 UTC, agustinustheo commented
> Please note that this PR will be approved first to catch up DeBio launch mainnet, but will become a tech debt for part that @agustinustheo 's comment

Then please create the issue in JIRA. @JackyRahman there's a conflict.

2021-12-22 06:18 UTC, agustinustheo approved these changes

2021-12-22 06:18 UTC, merged