feat: order rejected and binding eth address
debionetwork/debio-backend pull request #27
Opened 2021-08-12 03:17 UTC by elimSumanta

JIRA Link
https://blocksphere2020.atlassian.net/browse/DBIO-359
https://blocksphere2020.atlassian.net/browse/DBIO-362

change log:
- order rejected format payment to seller
- binding accountID with eth address

2021-08-12 03:39 UTC, kevinjanada requested changes

2021-08-12 03:39 UTC, kevinjanada commented on src/escrow/escrow.service.ts
> +      const tx = await this.forwardPaymentToSeller(buyerEthAddress, totalPrice);
function ini skalian kita bikin general aja mungkin ya?
forwardPaymentToUser mungkin?
krn kalau skarang forwardPaymentToSeller tapi ngirim nya ke buyer rada rancu rasanya

2021-08-12 03:39 UTC, kevinjanada commented on src/substrate/substrate.service.ts
> +  async bindingEthAddress(mnemonic: string, ethAddress: string) {
Spertinya kita harus cari cara lain. karena mnemonic itu seharusnya tidak boleh diketahui siapapun kecuali user.
Aku rasa kita buat endpoint untuk ngirim user DeBio aja, dengan syarat, dia belum pernah melakukan binding sebelumnya

2021-08-12 06:14 UTC, marcondol approved these changes

2021-08-12 11:41 UTC, elimSumanta commented on src/substrate/substrate.service.ts
> +  async bindingEthAddress(mnemonic: string, ethAddress: string) {
kita change logic yak ini. g jadi pakai mnemonic, haram.

2021-08-12 11:42 UTC, elimSumanta commented on src/escrow/escrow.service.ts
> +      const tx = await this.forwardPaymentToSeller(buyerEthAddress, totalPrice);
ok noted

2021-08-12 14:04 UTC, JackyRahman approved these changes

2021-10-31 08:28 UTC, JackyRahman commented
this PR not relevant, because extrinsics EthAddressSet deleted, and DB lab_requests deleted too

2021-10-31 08:28 UTC, closed without merging