[DBIO-2512 & DBIO-2513 & DBIO-2514 & DBIO-2515] Lab notification account verification
debionetwork/debio-backend pull request #347
Opened 2022-05-12 13:15 UTC by rubenkristian

### JIRA LINK
- https://blocksphere2020.atlassian.net/browse/DBIO-2512
- https://blocksphere2020.atlassian.net/browse/DBIO-2513
- https://blocksphere2020.atlassian.net/browse/DBIO-2514
- https://blocksphere2020.atlassian.net/browse/DBIO-2515

### Changelog
- notification for verified, rejected, revoked
- notification verification reward after reward success
- update unit test

2022-06-06 11:06 UTC, hilyds reviewed
beside the 1 minor comment, it looks good to me @rubenkristian

2022-06-07 02:55 UTC, hilyds approved these changes

2022-06-07 03:57 UTC, agustinustheo approved these changes

2022-06-07 03:57 UTC, hilyds commented on src/endpoints/verification/verification.service.ts
> +          from: null,
from: 'Debio Network',

2022-06-07 03:58 UTC, hilyds commented on src/endpoints/verification/verification.service.ts
> +            from: null,
from: 'Debio Network',

2022-06-07 04:48 UTC, hilyds requested changes

2022-06-07 04:48 UTC, hilyds commented on src/endpoints/verification/verification.service.ts
> +          entity_type: 'Lab',
entity_type: 'Verification',

2022-06-07 04:48 UTC, hilyds commented on src/endpoints/verification/verification.service.ts
> +            notificationInput.entity = 'Lab verified';
notificationInput.entity = 'Account verified';

2022-06-07 04:48 UTC, hilyds commented on src/endpoints/verification/verification.service.ts
> +            notificationInput.entity = 'Lab revoked';
notificationInput.entity = 'Account revoked';

2022-06-07 04:48 UTC, hilyds commented on src/endpoints/verification/verification.service.ts
> +            notificationInput.entity = 'Lab rejected';
notificationInput.entity = 'Account rejected';

2022-06-08 12:04 UTC, rubenkristian commented
![image](https://user-images.githubusercontent.com/56469224/172611838-1474bc6e-9ffe-4ffc-b393-30834bf8656c.png)

2022-06-09 06:57 UTC, merged