[Dbio 2516] Backend Notification Lab - Add New Service
debionetwork/debio-backend pull request #348
Opened 2022-05-12 13:35 UTC by rubenkristian

### JIRA LINK
- https://blocksphere2020.atlassian.net/browse/DBIO-2516

### Changelog
- insert notification after service event created
- update unit test service created event

2022-06-06 11:14 UTC, hilyds approved these changes

2022-06-07 02:57 UTC, hilyds commented on src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
> +      description: `Congrats! You have successfully added your new service - ${service.info.name}.`,
You've successfully added your new service - `${service.info.name}`.

2022-06-07 03:51 UTC, agustinustheo approved these changes

2022-06-07 04:01 UTC, hilyds commented on src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
> +      from: null,
from: 'Debio Network',

2022-06-07 05:35 UTC, agustinustheo requested changes
Please fix sonar cloud bug.

2022-06-07 09:42 UTC, hilyds approved these changes

2022-06-08 01:40 UTC, agustinustheo approved these changes

2022-06-08 01:40 UTC, merged