[DBIO-2517] notification: Lab - Reward from Completing Req Test from Service Requested
debionetwork/debio-backend pull request #352
Opened 2022-05-17 12:09 UTC by rubenkristian

### JIRA LINK
- https://blocksphere2020.atlassian.net/browse/DBIO-2517

### Changelog
- send notification to lab after completing request test

2022-06-06 11:55 UTC, hilyds requested changes

2022-06-06 11:55 UTC, hilyds commented on src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
> +          entity: 'OrderFulfilled',
entity should be `'Request Service Staking '`
![image](https://user-images.githubusercontent.com/37687466/172154005-cfabcd77-7a4c-438c-aa7e-63330bba52eb.png)

2022-06-06 11:55 UTC, hilyds commented on src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
> +          description: `Congrats! You’ve got ${servicePrice} DBIO as a reward for completing the request test for ${order.id} from the service requested`,
and `${order.id}` supposed to be tracking ID instead

2022-06-07 03:24 UTC, hilyds commented on src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
>          const servicePrice = +order.prices[0].value * debioToDai;
change this to totalPrice

2022-06-07 03:24 UTC, hilyds commented on src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
> +              description: `Congrats! You’ve received ${servicePrice} DBIO for completing the request test for ${order.dnaSampleTrackingId} from the service requested.`,
supposed to be totalPrice

2022-06-07 03:24 UTC, hilyds commented on src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
> +              description: `Congrats! You’ve got ${servicePrice} DBIO as a reward for completing the request test for ${order.id} from the service requested`,
supposed to be totalPrice

2022-06-07 03:24 UTC, hilyds commented on src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
>            convertToDbioUnitString(servicePrice / 10),
supposed to be totalPrice

2022-06-07 03:33 UTC, hilyds commented on src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
>            convertToDbioUnitString(servicePrice),
supposed to be totalPrice

2022-06-07 09:47 UTC, hilyds approved these changes

2022-06-08 01:38 UTC, agustinustheo approved these changes

2022-06-08 01:38 UTC, merged