[DBIO-2541] notification: Customer - Stake Amount Refunded
debionetwork/debio-backend pull request #370
Opened 2022-06-02 09:03 UTC by rubenkristian

### JIRA LINK
- https://blocksphere2020.atlassian.net/browse/DBIO-2541

### Changelog
- add new event service request staking amount refunded
- unit test staking amount refunded

2022-06-07 04:12 UTC, agustinustheo approved these changes

2022-06-07 04:19 UTC, hilyds requested changes

2022-06-07 04:19 UTC, hilyds commented on src/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.handler.ts
> +      description: `Your stake amount from staking ID ${requestId} has been refunded, kindly check your balance.`,
stake change to staked

2022-06-07 04:19 UTC, hilyds commented on test/unit/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.handler.spec.ts
> +        description: `Your stake amount from staking ID ${REQUEST_ID} has been refunded, kindly check your balance.`,
same changes, stake change to staked

2022-06-07 10:17 UTC, hilyds approved these changes

2022-06-08 12:55 UTC, rubenkristian commented
![image](https://user-images.githubusercontent.com/56469224/172621605-d75e5461-35bc-4f51-9196-7b64652b9923.png)

2022-06-09 05:37 UTC, merged