feat: endpoint Dna Collection Process category and testing
debionetwork/debio-backend pull request #392
Opened 2022-06-17 07:13 UTC by JackyRahman

### JIRA LINK
- https://blocksphere2020.atlassian.net/browse/DBIO-2588

### Changelog
- [feat: endpoint for dna collection process list](https://github.com/debionetwork/debio-backend/commit/77e871e735420ae423a13b04974ec3ed972275b0)
- [test: integration test dna collection process e2e](https://github.com/debionetwork/debio-backend/commit/cbb5de4b4c4c503b50fa7bd38f757f89e30ac98b)

2022-06-17 07:18 UTC, ciniiia approved these changes

2022-06-17 07:18 UTC, ciniiia commented on src/endpoints/category/dna-collection/dna-collection.controller.ts
> +}
lgtm

2022-06-18 05:07 UTC, agustinustheo requested changes

2022-06-18 05:07 UTC, agustinustheo commented on src/endpoints/email/email.controller.ts
> +    await this.notificationService.insert(notificationRegistration);
Notification services shouldn't exist within endpoints.

2022-06-18 05:08 UTC, agustinustheo commented
Also please fix the conflicts, and follow the guidelines from here: https://github.com/debionetwork/debio-backend/pull/389

2022-06-19 09:14 UTC, JackyRahman commented on src/endpoints/email/email.controller.ts
> +    await this.notificationService.insert(notificationRegistration);
updated

2022-06-20 15:49 UTC, agustinustheo approved these changes

2022-06-20 15:50 UTC, agustinustheo approved these changes

2022-06-20 15:54 UTC, merged