Send mail function
debionetwork/debio-backend pull request #45
Opened 2021-08-31 04:17 UTC by JackyRahman

### Debio 263
url: [https://blocksphere2020.atlassian.net/browse/DBIO-263](https://blocksphere2020.atlassian.net/browse/DBIO-263)

### [Back End] Function send email for staking services
build module, service, template for function send mail notification 
how to use function ready in mail.service.ts beetween line 35 and 55

2021-09-01 08:50 UTC, kevinjanada requested changes
Please review

2021-09-01 08:50 UTC, kevinjanada commented on src/mail/templates/notification.hbs
> +{{!-- <p>If you did not request this email you can safely ignore it.</p> --}}
mas ini hapus aja ya

2021-09-01 08:50 UTC, kevinjanada commented on src/app.module.ts
> +    // SubstrateIndexedDataModule,
Ini kenapa di comment ya mas?

2021-09-02 08:19 UTC, JackyRahman commented
> Please review

Sudah saya update dan upstream mas hehe

2021-09-03 06:52 UTC, kevinjanada approved these changes
Looks good

2021-09-03 06:55 UTC, kevinjanada requested changes
Mas @JackyRahman tlg resolve conflict nya dulu yah.
Soalnya commit nya kepanjangan klo aku resolve di github langsung.

2021-09-03 07:13 UTC, kevinjanada approved these changes

2021-09-03 07:13 UTC, merged