Send gas fee DBIO to Lab on success order payment from customer
debionetwork/debio-backend pull request #46
Opened 2021-08-31 05:39 UTC by christianruben

get account id lab (seller_id property) from order detail, and check if balance not enough send 1 DBIO to lab

2021-08-31 06:59 UTC, JackyRahman approved these changes

2021-09-01 03:43 UTC, kevinjanada requested changes
Please review the change request

2021-09-01 03:43 UTC, kevinjanada commented on src/escrow/escrow.service.ts
> +      if(balance.free.isZero()) {
@christianruben ben, ini minta tolong diganti jadi kurang dari 0.5 aja ya. takutnya kalo bener2 kosong si lab udah keburu ga bisa ngapa2in

2021-09-01 08:51 UTC, kevinjanada approved these changes

2021-09-01 08:52 UTC, merged