Email
debionetwork/debio-backend pull request #97
Opened 2021-11-02 08:50 UTC by JackyRahman

### Debio 928, 866, 913
[https://blocksphere2020.atlassian.net/browse/DBIO-928](https://blocksphere2020.atlassian.net/browse/DBIO-928)
[https://blocksphere2020.atlassian.net/browse/DBIO-866](https://blocksphere2020.atlassian.net/browse/DBIO-866)
[https://blocksphere2020.atlassian.net/browse/DBIO-913](https://blocksphere2020.atlassian.net/browse/DBIO-913)

### Debio 928 API Reward

- add flow bounty

### Debio 866 Email

- create template for send email when lab register
- create fucntion for send email when lab register
- fixing template and fuction for send email when customer staking request service

### Debio 913 Lab indexer

- add query and filter for service flow
- add field verification

2021-11-02 12:04 UTC, rubenkristian approved these changes
looks good to me

2021-11-02 14:29 UTC, agustinustheo requested changes

2021-11-02 14:29 UTC, agustinustheo commented on src/mail/mail.service.ts
> +      to: 'jackyrahman443@gmail.com',
Why are you hardcoding this?

2021-11-02 14:29 UTC, agustinustheo commented on src/mail/mail.service.ts
> +  // =======testing and how to use this function===========
Please remove unnecessary comments like these.

2021-11-02 14:29 UTC, agustinustheo commented on src/substrate/geneticTestingEvent.ts
> +      await this.api.query.orders.orders(dataStaked.order_id)
You should separate queries to the blockchain inside a `polkadot-providers` folder, please refer to frontend: https://github.com/debionetwork/debio-customer-ui/tree/development/src/common/lib/polkadot-provider

2021-11-03 04:03 UTC, agustinustheo approved these changes

2021-11-03 04:04 UTC, merged